### ISSUE TITLE
Interndevops

### ISSUE THREAD

**Issue by Patelvibhuti** [ignitedotdev/intern-task#1]

**Comment by Horlawhumy-dev** [comment]
Hi, I am Arafat from Nigeria pka HaroffCode. I didn't see application but can I apply by completing this task?

**Comment by Horlawhumy-dev** [comment]
@nneyen @Patelvibhuti @libracoder

**Comment by Oyoh-Edmond** [comment]
i have completed the task and sent it your mail but no response yet
